/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Fri Jul 04 07:22:24 GMT 2025
 */

package org.apache.openjpa.kernel;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;
import org.junit.After;
import org.junit.AfterClass;
import org.junit.Before;
import org.junit.BeforeClass;

@EvoSuiteClassExclude
public class ManagedCache_ESTest_scaffolding {

  @org.junit.Rule
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) System.getProperties().clone();

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "org.apache.openjpa.kernel.ManagedCache"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = SandboxMode.RECOMMENDED;
    Sandbox.initializeSecurityManagerForSUT();
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    System.setProperties((java.util.Properties) defaultProperties.clone());
  } 

  @Before
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    Sandbox.goingToExecuteSUTCode();
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    Sandbox.doneWithExecutingSUTCode();
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    System.setProperties((java.util.Properties) defaultProperties.clone());
    System.setProperty("user.dir", "/Users/gaiameola/Dev/ISW2/openjpa/openjpa-kernel");
    System.setProperty("java.io.tmpdir", "/var/folders/6s/z3dxnqjs6x71zzqgsdm1nwk40000gn/T/");
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(ManagedCache_ESTest_scaffolding.class.getClassLoader() ,
      "org.apache.openjpa.lib.util.StreamResourceBundleProvider",
      "org.apache.openjpa.lib.util.collections.AbstractReferenceMap$ReferenceEntrySet",
      "org.apache.openjpa.enhance.PersistenceCapable",
      "org.apache.openjpa.event.CallbackModes",
      "org.apache.openjpa.lib.util.ZipResourceBundleProvider",
      "org.apache.openjpa.lib.util.collections.AbstractHashedMap",
      "org.apache.openjpa.meta.MetaDataModes",
      "org.apache.openjpa.lib.util.collections.AbstractReferenceMap$ReferenceValuesIterator",
      "org.apache.openjpa.meta.ClassMetaData",
      "org.apache.openjpa.util.GeneralException",
      "org.apache.openjpa.util.OptimisticException",
      "org.apache.openjpa.lib.util.SizedMap",
      "org.apache.openjpa.kernel.BrokerImpl",
      "org.apache.openjpa.lib.conf.ValueListener",
      "org.apache.openjpa.meta.MetaDataContext",
      "org.apache.openjpa.util.UserException",
      "org.apache.openjpa.lib.util.collections.IterableMap",
      "org.apache.openjpa.kernel.StoreQuery",
      "org.apache.openjpa.lib.util.collections.AbstractHashedMap$HashEntry",
      "org.apache.openjpa.lib.util.collections.AbstractReferenceMap$ReferenceKeySet",
      "org.apache.openjpa.kernel.LockScopes",
      "org.apache.openjpa.lib.util.collections.AbstractReferenceMap$ReferenceStrength",
      "org.apache.openjpa.lib.util.SimpleResourceBundleProvider",
      "org.apache.openjpa.kernel.Broker",
      "org.apache.openjpa.lib.util.collections.AbstractReferenceMap",
      "org.apache.openjpa.lib.meta.SourceTracker",
      "org.apache.openjpa.kernel.AutoDetach",
      "org.apache.openjpa.kernel.QueryFlushModes",
      "org.apache.openjpa.lib.util.collections.KeyValue",
      "org.apache.openjpa.lib.util.J2DoPrivHelper",
      "org.apache.openjpa.lib.util.ReferenceMap",
      "org.apache.openjpa.kernel.LockLevels",
      "org.apache.openjpa.util.OpenJPAException",
      "org.apache.openjpa.kernel.FindCallbacks",
      "org.apache.openjpa.lib.util.collections.AbstractReferenceMap$ReferenceValues",
      "org.apache.openjpa.kernel.StoreContext",
      "org.apache.openjpa.util.UnsupportedException",
      "org.apache.openjpa.meta.ValueMetaData",
      "org.apache.openjpa.util.ObjectNotFoundException",
      "org.apache.openjpa.util.InvalidStateException",
      "org.apache.openjpa.kernel.Seq",
      "org.apache.openjpa.kernel.InverseManager",
      "org.apache.openjpa.lib.util.J2DoPrivHelper$5",
      "org.apache.openjpa.kernel.Query",
      "org.apache.openjpa.kernel.StoreManager",
      "org.apache.openjpa.kernel.BrokerFactory",
      "org.apache.openjpa.kernel.LockManager",
      "org.apache.openjpa.lib.util.collections.AbstractReferenceMap$ReferenceBaseIterator",
      "org.apache.openjpa.kernel.OpenJPAStateManager",
      "org.apache.openjpa.event.LifecycleEventManager",
      "org.apache.openjpa.meta.FieldMetaData",
      "org.apache.openjpa.kernel.RestoreState",
      "org.apache.openjpa.lib.conf.Configurable",
      "org.apache.openjpa.lib.util.collections.AbstractHashedMap$Values",
      "org.apache.openjpa.lib.util.Closeable",
      "org.apache.openjpa.lib.util.collections.AbstractReferenceMap$ReferenceEntry",
      "org.apache.openjpa.lib.util.ReferenceHashMap$AccessibleEntry",
      "org.apache.openjpa.kernel.SaveFieldManager",
      "org.apache.openjpa.lib.conf.Configuration",
      "org.apache.openjpa.util.WrappedException",
      "org.apache.openjpa.lib.util.collections.ReferenceMap",
      "org.apache.openjpa.lib.util.collections.AbstractHashedMap$KeySet",
      "org.apache.openjpa.lib.util.collections.AbstractHashedMap$EntrySet",
      "org.apache.openjpa.enhance.StateManager",
      "org.apache.openjpa.lib.util.ResourceBundleProvider",
      "org.apache.openjpa.kernel.DelegatingStoreManager",
      "org.apache.openjpa.util.InternalException",
      "org.apache.openjpa.kernel.AutoClear",
      "org.apache.openjpa.enhance.FieldConsumer",
      "org.apache.openjpa.kernel.DetachState",
      "org.apache.openjpa.kernel.QueryContext",
      "org.apache.openjpa.kernel.ClearFieldManager",
      "org.apache.openjpa.kernel.AbstractFieldManager",
      "org.apache.openjpa.lib.util.ReferenceHashMap",
      "org.apache.openjpa.lib.util.collections.MapIterator",
      "org.apache.openjpa.kernel.FetchConfiguration",
      "org.apache.openjpa.ee.ManagedRuntime",
      "org.apache.openjpa.kernel.Extent",
      "org.apache.openjpa.kernel.AbstractBrokerFactory",
      "org.apache.openjpa.lib.xml.Commentable",
      "org.apache.openjpa.kernel.FinalizingBrokerImpl",
      "org.apache.openjpa.lib.util.Localizer",
      "jakarta.transaction.Synchronization",
      "org.apache.openjpa.kernel.StateManagerImpl",
      "org.apache.openjpa.kernel.ManagedCache",
      "org.apache.openjpa.enhance.FieldSupplier",
      "org.apache.openjpa.enhance.FieldManager",
      "org.apache.openjpa.kernel.PCState",
      "org.apache.openjpa.util.CallbackException",
      "org.apache.openjpa.util.NoTransactionException",
      "org.apache.openjpa.kernel.OpCallbacks",
      "org.apache.openjpa.conf.OpenJPAConfiguration",
      "org.apache.openjpa.meta.Extensions",
      "org.apache.openjpa.util.StoreException",
      "org.apache.openjpa.kernel.QueryOperations",
      "org.apache.openjpa.util.ExceptionInfo",
      "org.apache.openjpa.util.RuntimeExceptionTranslator",
      "org.apache.openjpa.kernel.ConnectionRetainModes"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(ManagedCache_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "org.apache.openjpa.lib.util.SimpleResourceBundleProvider",
      "org.apache.openjpa.lib.util.StreamResourceBundleProvider",
      "org.apache.openjpa.lib.util.ZipResourceBundleProvider",
      "org.apache.openjpa.lib.util.Localizer",
      "org.apache.openjpa.lib.util.J2DoPrivHelper",
      "org.apache.openjpa.lib.util.J2DoPrivHelper$5",
      "org.apache.openjpa.kernel.ManagedCache",
      "org.apache.openjpa.lib.util.collections.AbstractReferenceMap$ReferenceStrength",
      "org.apache.openjpa.lib.util.concurrent.ConcurrentReferenceHashMap",
      "org.apache.openjpa.lib.util.concurrent.ConcurrentReferenceHashSet",
      "org.apache.openjpa.lib.util.collections.MapBackedSet",
      "org.apache.openjpa.enhance.PCRegistry",
      "org.apache.openjpa.util.ImplHelper$1",
      "org.apache.openjpa.util.ImplHelper",
      "org.apache.openjpa.lib.util.J2DoPrivHelper$1",
      "org.apache.openjpa.lib.conf.ConfigurationImpl",
      "org.apache.openjpa.conf.OpenJPAConfigurationImpl",
      "org.apache.openjpa.lib.conf.Value",
      "org.apache.openjpa.lib.conf.ObjectValue",
      "org.apache.openjpa.lib.conf.PluginValue",
      "org.apache.openjpa.lib.conf.Configurations",
      "org.apache.openjpa.lib.util.StringUtil",
      "org.apache.openjpa.lib.conf.StringValue",
      "org.apache.openjpa.util.StoreFacadeTypeRegistry",
      "org.apache.openjpa.lib.util.concurrent.AbstractConcurrentEventManager",
      "org.apache.openjpa.event.BrokerFactoryEventManager",
      "org.apache.openjpa.lib.util.J2DoPrivHelper$49",
      "org.apache.openjpa.lib.util.J2DoPrivHelper$16",
      "org.apache.openjpa.lib.util.MultiClassLoader",
      "org.apache.openjpa.lib.util.J2DoPrivHelper$40",
      "org.apache.openjpa.lib.util.Services",
      "org.apache.openjpa.lib.util.J2DoPrivHelper$15",
      "org.apache.openjpa.lib.util.Localizer$Message",
      "org.apache.openjpa.lib.conf.ProductDerivations",
      "org.apache.openjpa.conf.BrokerFactoryValue",
      "org.apache.openjpa.kernel.BrokerImpl",
      "org.apache.openjpa.util.OpenJPAException",
      "org.apache.openjpa.util.UserException",
      "org.apache.openjpa.util.InvalidStateException",
      "org.apache.openjpa.util.NoTransactionException",
      "org.apache.openjpa.kernel.AbstractBrokerFactory",
      "org.apache.openjpa.lib.util.collections.AbstractHashedMap",
      "org.apache.openjpa.lib.util.collections.AbstractReferenceMap",
      "org.apache.openjpa.lib.util.collections.ReferenceMap",
      "org.apache.openjpa.lib.util.ReferenceHashMap",
      "org.apache.openjpa.kernel.FinalizingBrokerImpl",
      "org.apache.openjpa.util.Exceptions$1",
      "org.apache.openjpa.util.Exceptions",
      "org.apache.openjpa.kernel.AttachManager",
      "org.apache.openjpa.kernel.jpql.JPQLExpressionBuilder$ParsedJPQL",
      "org.apache.openjpa.kernel.exps.Val",
      "org.apache.openjpa.kernel.exps.Null",
      "org.apache.openjpa.kernel.exps.InMemoryExpressionFactory",
      "org.apache.openjpa.meta.MetaDataRepository",
      "org.apache.openjpa.event.LifecycleEventManager$ListenerList",
      "org.apache.openjpa.meta.Extensions",
      "org.apache.openjpa.meta.AccessCode",
      "org.apache.openjpa.meta.ClassMetaData",
      "org.apache.openjpa.meta.LifecycleMetaData",
      "org.apache.openjpa.lib.instrumentation.AbstractInstrument",
      "org.apache.openjpa.instrumentation.AbstractQueryCacheInstrument",
      "org.apache.openjpa.instrumentation.jmx.QueryCacheJMXInstrument",
      "org.apache.openjpa.kernel.PNewState",
      "org.apache.openjpa.kernel.PCleanState",
      "org.apache.openjpa.kernel.PDirtyState",
      "org.apache.openjpa.kernel.PDeletedState",
      "org.apache.openjpa.kernel.PNewDeletedState",
      "org.apache.openjpa.kernel.PNewProvisionalState",
      "org.apache.openjpa.kernel.PNonTransState",
      "org.apache.openjpa.kernel.PNonTransDirtyState",
      "org.apache.openjpa.kernel.PNonTransNewState",
      "org.apache.openjpa.kernel.PNonTransDeletedState",
      "org.apache.openjpa.kernel.HollowState",
      "org.apache.openjpa.kernel.TransientState",
      "org.apache.openjpa.kernel.TCleanState",
      "org.apache.openjpa.kernel.TDirtyState",
      "org.apache.openjpa.kernel.TLoadedState",
      "org.apache.openjpa.kernel.ECopyState",
      "org.apache.openjpa.kernel.ECleanState",
      "org.apache.openjpa.kernel.EDirtyState",
      "org.apache.openjpa.kernel.EDeletedState",
      "org.apache.openjpa.kernel.ENonTransState",
      "org.apache.openjpa.kernel.PNewFlushedDeletedState",
      "org.apache.openjpa.kernel.PNewFlushedDeletedFlushedState",
      "org.apache.openjpa.kernel.PDeletedFlushedState",
      "org.apache.openjpa.kernel.PCState",
      "org.apache.openjpa.kernel.StateManagerImpl",
      "org.apache.openjpa.kernel.jpql.JPQLParser",
      "org.apache.openjpa.kernel.AbstractStoreQuery",
      "org.apache.openjpa.kernel.exps.StringContains",
      "org.apache.openjpa.kernel.exps.WildcardMatch",
      "org.apache.openjpa.kernel.ExpressionStoreQuery",
      "org.apache.openjpa.kernel.AbstractStoreQuery$AbstractExecutor",
      "org.apache.openjpa.kernel.ExpressionStoreQuery$AbstractExpressionExecutor",
      "org.apache.openjpa.kernel.ExpressionStoreQuery$DataStoreExecutor",
      "org.apache.openjpa.util.UnsupportedException",
      "org.apache.openjpa.kernel.TransferFieldManager",
      "org.apache.openjpa.kernel.SingleFieldManager",
      "org.apache.openjpa.kernel.DelegatingBroker",
      "org.apache.openjpa.kernel.exps.QueryExpressions",
      "org.apache.openjpa.lib.util.collections.AbstractLinkedMap",
      "org.apache.openjpa.lib.util.collections.LinkedMap",
      "org.apache.openjpa.lib.util.collections.AbstractHashedMap$HashEntry",
      "org.apache.openjpa.lib.util.collections.AbstractLinkedMap$LinkEntry",
      "org.apache.openjpa.lib.util.OrderedMap",
      "org.apache.openjpa.kernel.StoreQuery",
      "org.apache.openjpa.kernel.AttachStrategy",
      "org.apache.openjpa.kernel.VersionAttachStrategy",
      "org.apache.openjpa.util.StoreException",
      "org.apache.openjpa.util.ObjectNotFoundException",
      "org.apache.openjpa.kernel.exps.CandidatePath",
      "org.apache.openjpa.kernel.FetchConfigurationImpl",
      "org.apache.openjpa.kernel.FetchConfigurationImpl$ConfigurationState",
      "org.apache.openjpa.kernel.DataCacheRetrieveMode",
      "org.apache.openjpa.kernel.DataCacheStoreMode",
      "org.apache.openjpa.util.GeneralException",
      "org.apache.openjpa.kernel.QueryImpl",
      "org.apache.openjpa.lib.util.ReferenceHashSet$1",
      "org.apache.openjpa.lib.util.ReferenceHashSet",
      "org.apache.openjpa.kernel.ExtentImpl",
      "org.apache.openjpa.lib.rop.AbstractResultList",
      "org.apache.openjpa.lib.rop.AbstractNonSequentialResultList",
      "org.apache.openjpa.lib.rop.WindowResultList",
      "org.apache.openjpa.enhance.ReflectingPersistenceCapable",
      "org.apache.openjpa.kernel.DelegatingStoreManager",
      "org.apache.openjpa.kernel.ROPStoreManager",
      "org.apache.openjpa.kernel.AutoDetach",
      "org.apache.openjpa.kernel.DetachedValueStateManager",
      "org.apache.openjpa.kernel.ExpressionStoreQuery$InMemoryExecutor",
      "org.apache.openjpa.kernel.AbstractFieldManager",
      "org.apache.openjpa.kernel.ClearFieldManager",
      "org.apache.openjpa.kernel.SavepointFieldManager",
      "org.apache.openjpa.util.InternalException",
      "org.apache.openjpa.kernel.BrokerImpl$ManagedObjectCollection",
      "org.apache.openjpa.kernel.DelegatingQuery",
      "org.apache.openjpa.kernel.DelegatingFetchConfiguration",
      "org.apache.openjpa.kernel.exps.Context",
      "org.apache.openjpa.kernel.exps.SubQ",
      "org.apache.openjpa.util.MetaDataException",
      "org.apache.openjpa.kernel.MethodStoreQuery",
      "org.apache.openjpa.lib.util.StringDistance",
      "org.apache.openjpa.kernel.DetachManager",
      "org.apache.openjpa.datacache.AbstractQueryCache",
      "org.apache.openjpa.datacache.ConcurrentQueryCache",
      "org.apache.openjpa.datacache.AbstractQueryCache$EvictPolicy",
      "org.apache.openjpa.datacache.QueryKey",
      "org.apache.openjpa.datacache.DelegatingQueryCache",
      "org.apache.openjpa.lib.rop.ListResultList",
      "org.apache.openjpa.lib.rop.EagerResultList",
      "org.apache.openjpa.datacache.AbstractDataCache",
      "org.apache.openjpa.datacache.ConcurrentDataCache",
      "org.apache.openjpa.datacache.CacheStatisticsImpl",
      "org.apache.openjpa.lib.rop.ListResultObjectProvider",
      "org.apache.openjpa.kernel.exps.AbstractExpressionBuilder",
      "org.apache.openjpa.kernel.jpql.JPQLExpressionBuilder",
      "org.apache.openjpa.kernel.ExpressionStoreQuery$1",
      "org.apache.openjpa.kernel.DetachedStateManager",
      "org.apache.openjpa.lib.rop.RandomAccessResultList",
      "org.apache.openjpa.lib.util.collections.AbstractReferenceMap$ReferenceEntry",
      "org.apache.openjpa.lib.util.collections.AbstractReferenceMap$WeakRef",
      "org.apache.openjpa.kernel.DelegatingExtent",
      "org.apache.openjpa.datacache.DataCacheManagerImpl",
      "org.apache.openjpa.datacache.DefaultCacheDistributionPolicy",
      "jakarta.jms.JMSException",
      "org.apache.openjpa.datacache.PartitionedDataCache",
      "org.apache.openjpa.datacache.DelegatingDataCache",
      "org.apache.openjpa.lib.rop.AbstractListIterator",
      "org.apache.openjpa.lib.rop.ResultListIterator",
      "org.apache.openjpa.lib.rop.SimpleResultList",
      "org.apache.openjpa.datacache.QueryResult",
      "org.apache.openjpa.lib.rop.MergedResultObjectProvider",
      "org.apache.openjpa.ee.AbstractManagedRuntime",
      "org.apache.openjpa.ee.WLSManagedRuntime",
      "org.apache.openjpa.lib.rop.SoftRandomAccessResultList",
      "org.apache.openjpa.lib.rop.AbstractNonSequentialResultList$Itr",
      "org.apache.openjpa.lib.rop.RangeResultObjectProvider",
      "org.apache.openjpa.kernel.ObjectIdStateManager",
      "org.apache.openjpa.kernel.exps.UnaryMathVal",
      "org.apache.openjpa.kernel.exps.NaturalLogarithm",
      "org.apache.openjpa.kernel.exps.Exponential",
      "org.apache.openjpa.kernel.exps.Floor",
      "org.apache.openjpa.kernel.AbstractPCData",
      "org.apache.openjpa.kernel.PCDataImpl",
      "org.apache.openjpa.datacache.DataCachePCDataImpl",
      "org.apache.openjpa.lib.rop.AbstractSequentialResultList",
      "org.apache.openjpa.lib.rop.LazyForwardResultList",
      "org.apache.openjpa.kernel.StoreContext",
      "org.apache.openjpa.meta.XMLFieldMetaData",
      "org.apache.openjpa.meta.JavaTypes",
      "org.apache.openjpa.kernel.MethodStoreQuery$MethodExecutor",
      "org.apache.openjpa.ee.JNDIManagedRuntime",
      "org.apache.openjpa.kernel.DelegatingSeq",
      "org.apache.openjpa.ee.RegistryManagedRuntime",
      "org.apache.openjpa.ee.OSGiManagedRuntime",
      "org.apache.openjpa.ee.WASRegistryManagedRuntime",
      "org.apache.openjpa.lib.util.TypedProperties",
      "org.apache.openjpa.lib.util.Options$EmptyOptions",
      "org.apache.openjpa.lib.util.Options",
      "org.apache.openjpa.conf.MetaDataRepositoryValue",
      "org.apache.openjpa.lib.conf.PluginListValue",
      "org.apache.openjpa.conf.NoOpCacheMarshaller",
      "org.apache.openjpa.conf.CacheMarshallersValue",
      "org.apache.openjpa.ee.InvocationManagedRuntime",
      "org.apache.openjpa.kernel.exps.CurrentDate",
      "org.apache.openjpa.datacache.TypeBasedCacheDistributionPolicy",
      "org.apache.openjpa.util.ClassResolverImpl",
      "org.apache.openjpa.meta.QueryMetaData",
      "org.apache.openjpa.ee.SunOneManagedRuntime",
      "org.apache.openjpa.ee.WASManagedRuntime",
      "org.apache.openjpa.meta.FieldMetaData",
      "org.apache.openjpa.util.MultiLoaderClassResolver",
      "org.apache.xbean.asm9.Type",
      "org.apache.openjpa.util.ProxyManagerImpl",
      "org.apache.openjpa.util.GeneratedClasses",
      "org.apache.openjpa.lib.util.ClassUtil",
      "org.apache.xbean.asm9.ClassVisitor",
      "org.apache.xbean.asm9.ClassWriter",
      "org.apache.xbean.asm9.SymbolTable",
      "org.apache.xbean.asm9.ByteVector",
      "org.apache.xbean.asm9.Symbol",
      "org.apache.xbean.asm9.SymbolTable$Entry",
      "org.apache.openjpa.util.asm.ClassWriterTracker",
      "org.apache.xbean.asm9.Attribute",
      "org.apache.openjpa.util.asm.RedefinedAttribute",
      "org.apache.openjpa.util.asm.AsmHelper",
      "org.apache.xbean.asm9.MethodVisitor",
      "org.apache.xbean.asm9.MethodWriter",
      "org.apache.xbean.asm9.Label",
      "org.apache.xbean.asm9.Frame",
      "org.apache.xbean.asm9.FieldVisitor",
      "org.apache.xbean.asm9.FieldWriter",
      "org.apache.xbean.asm9.AnnotationVisitor",
      "org.apache.xbean.asm9.AnnotationWriter",
      "org.apache.xbean.asm9.Handler",
      "org.apache.openjpa.util.ClassLoaderProxyService",
      "org.apache.openjpa.util.ClassLoaderProxyService$ProxiesClassLoader",
      "org.apache.openjpa.lib.util.J2DoPrivHelper$11",
      "org.apache.openjpa.meta.XMLClassMetaData",
      "org.apache.openjpa.ee.AutomaticManagedRuntime",
      "org.apache.openjpa.lib.util.J2DoPrivHelper$4",
      "org.apache.openjpa.ee.RegistryManagedRuntime$TransactionManagerRegistryFacade",
      "org.apache.openjpa.kernel.exps.Args",
      "org.apache.openjpa.kernel.exps.All",
      "org.apache.openjpa.kernel.exps.CurrentTemporal",
      "org.apache.openjpa.kernel.exps.UnboundVariable",
      "org.apache.openjpa.kernel.exps.GetMapValue",
      "org.apache.openjpa.kernel.UUIDType4HexSeq",
      "org.apache.openjpa.lib.util.ParseException",
      "org.apache.openjpa.kernel.UUIDHexSeq",
      "org.apache.openjpa.lib.util.collections.AbstractHashedMap$Values",
      "org.apache.openjpa.lib.util.collections.AbstractReferenceMap$ReferenceValues",
      "org.apache.openjpa.lib.util.collections.AbstractReferenceMap$ReferenceBaseIterator",
      "org.apache.openjpa.lib.util.collections.AbstractReferenceMap$ReferenceValuesIterator"
    );
  }
}
