/*
 * This file was automatically generated by EvoSuite
 * Fri Jul 04 07:22:24 GMT 2025
 */

package org.apache.openjpa.kernel;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;

import java.util.Collection;

import static org.evosuite.runtime.EvoAssertions.verifyException;
import static org.junit.Assert.*;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = false, resetStaticState = true, separateClassLoader = false)
public class ManagedCache_ESTest extends ManagedCache_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      FinalizingBrokerImpl finalizingBrokerImpl0 = new FinalizingBrokerImpl();
      ManagedCache managedCache0 = new ManagedCache(finalizingBrokerImpl0);
      // Undeclared exception!
      try { 
        managedCache0.remove(finalizingBrokerImpl0, (StateManagerImpl) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.openjpa.kernel.ManagedCache", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      FinalizingBrokerImpl finalizingBrokerImpl0 = new FinalizingBrokerImpl();
      ManagedCache managedCache0 = new ManagedCache(finalizingBrokerImpl0);
      // Undeclared exception!
      try { 
        managedCache0.commitNew((Object) null, (StateManagerImpl) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.openjpa.kernel.ManagedCache", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      FinalizingBrokerImpl finalizingBrokerImpl0 = new FinalizingBrokerImpl();
      ManagedCache managedCache0 = new ManagedCache(finalizingBrokerImpl0);
      // Undeclared exception!
      try { 
        managedCache0.add((StateManagerImpl) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.openjpa.kernel.ManagedCache", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      ManagedCache managedCache0 = null;
      try {
        managedCache0 = new ManagedCache((BrokerImpl) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.openjpa.kernel.ManagedCache", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      FinalizingBrokerImpl finalizingBrokerImpl0 = new FinalizingBrokerImpl();
      ManagedCache managedCache0 = new ManagedCache(finalizingBrokerImpl0);
      managedCache0.dirtyCheck();
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      FinalizingBrokerImpl finalizingBrokerImpl0 = new FinalizingBrokerImpl();
      ManagedCache managedCache0 = new ManagedCache(finalizingBrokerImpl0);
      managedCache0.clearNew();
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      BrokerImpl brokerImpl0 = new BrokerImpl();
      ManagedCache managedCache0 = new ManagedCache(brokerImpl0);
      managedCache0.clear();
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      FinalizingBrokerImpl finalizingBrokerImpl0 = new FinalizingBrokerImpl();
      ManagedCache managedCache0 = new ManagedCache(finalizingBrokerImpl0);
      Collection<StateManagerImpl> collection0 = managedCache0.copy();
      assertNotNull(collection0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      FinalizingBrokerImpl finalizingBrokerImpl0 = new FinalizingBrokerImpl();
      ManagedCache managedCache0 = new ManagedCache(finalizingBrokerImpl0);
      // Undeclared exception!
      try { 
        managedCache0.assignObjectId((Object) null, (StateManagerImpl) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.openjpa.kernel.ManagedCache", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      BrokerImpl brokerImpl0 = new BrokerImpl();
      ManagedCache managedCache0 = new ManagedCache(brokerImpl0);
      managedCache0.persist((StateManagerImpl) null);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      BrokerImpl brokerImpl0 = new BrokerImpl();
      ManagedCache managedCache0 = new ManagedCache(brokerImpl0);
      StateManagerImpl stateManagerImpl0 = managedCache0.getById(managedCache0, true);
      assertNull(stateManagerImpl0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      BrokerImpl brokerImpl0 = new BrokerImpl();
      ManagedCache managedCache0 = new ManagedCache(brokerImpl0);
      StateManagerImpl stateManagerImpl0 = managedCache0.getById((Object) null, false);
      assertNull(stateManagerImpl0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      FinalizingBrokerImpl finalizingBrokerImpl0 = new FinalizingBrokerImpl();
      ManagedCache managedCache0 = new ManagedCache(finalizingBrokerImpl0);
      StateManagerImpl stateManagerImpl0 = managedCache0.getById(finalizingBrokerImpl0, false);
      assertNull(stateManagerImpl0);
  }
}
