/*
 * This file was automatically generated by EvoSuite
 * Fri Jul 04 07:39:38 GMT 2025
 */

package org.apache.openjpa.jdbc.identifier;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.openjpa.jdbc.conf.JDBCConfiguration;
import org.apache.openjpa.jdbc.conf.JDBCConfigurationImpl;
import org.apache.openjpa.jdbc.identifier.DBIdentifier;
import org.apache.openjpa.jdbc.identifier.DBIdentifierUtilImpl;
import org.apache.openjpa.jdbc.identifier.DefaultIdentifierConfiguration;
import org.apache.openjpa.jdbc.meta.MappingDefaultsImpl;
import org.apache.openjpa.jdbc.schema.Column;
import org.apache.openjpa.jdbc.schema.DynamicSchemaFactory;
import org.apache.openjpa.jdbc.schema.LazySchemaFactory;
import org.apache.openjpa.jdbc.schema.NameSet;
import org.apache.openjpa.jdbc.schema.Schema;
import org.apache.openjpa.jdbc.schema.SchemaGroup;
import org.apache.openjpa.jdbc.schema.Table;
import org.apache.openjpa.jdbc.sql.AccessDictionary;
import org.apache.openjpa.jdbc.sql.CacheDictionary;
import org.apache.openjpa.jdbc.sql.DBDictionary;
import org.apache.openjpa.jdbc.sql.EmpressDictionary;
import org.apache.openjpa.jdbc.sql.FoxProDictionary;
import org.apache.openjpa.jdbc.sql.HerdDBDictionary;
import org.apache.openjpa.jdbc.sql.IngresDictionary;
import org.apache.openjpa.jdbc.sql.JDataStoreDictionary;
import org.apache.openjpa.jdbc.sql.MySQLDictionary;
import org.apache.openjpa.jdbc.sql.PostgresDictionary;
import org.apache.openjpa.jdbc.sql.SolidDBDictionary;
import org.apache.openjpa.lib.conf.ConfigurationImpl;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class DBIdentifierUtilImpl_ESTest extends DBIdentifierUtilImpl_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test000()  throws Throwable  {
      DBDictionary dBDictionary0 = new DBDictionary();
      DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(dBDictionary0);
      JDBCConfigurationImpl jDBCConfigurationImpl0 = new JDBCConfigurationImpl(true, true);
      dBIdentifierUtilImpl0.setConfiguration(jDBCConfigurationImpl0);
      assertFalse(jDBCConfigurationImpl0.isReadOnly());
  }

  @Test(timeout = 4000)
  public void test001()  throws Throwable  {
      FoxProDictionary foxProDictionary0 = new FoxProDictionary();
      DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(foxProDictionary0);
      DBIdentifier.DBIdentifierType dBIdentifier_DBIdentifierType0 = DBIdentifier.DBIdentifierType.SCHEMA;
      DBIdentifier dBIdentifier0 = DBIdentifier.newIdentifier("", dBIdentifier_DBIdentifierType0, true, false);
      String string0 = dBIdentifierUtilImpl0.toDBName(dBIdentifier0);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test002()  throws Throwable  {
      DefaultIdentifierConfiguration defaultIdentifierConfiguration0 = new DefaultIdentifierConfiguration();
      DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(defaultIdentifierConfiguration0);
      String string0 = dBIdentifierUtilImpl0.toDBName((String) null, false);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test003()  throws Throwable  {
      DefaultIdentifierConfiguration defaultIdentifierConfiguration0 = new DefaultIdentifierConfiguration();
      DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(defaultIdentifierConfiguration0);
      String string0 = dBIdentifierUtilImpl0.toDBName(" <)bW8]e,c`1>E~f?)51", false);
      assertNotNull(string0);
      assertEquals(" <)bW8]e,c`1>E~f?)51", string0);
  }

  @Test(timeout = 4000)
  public void test004()  throws Throwable  {
      DefaultIdentifierConfiguration defaultIdentifierConfiguration0 = new DefaultIdentifierConfiguration();
      DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(defaultIdentifierConfiguration0);
      String string0 = dBIdentifierUtilImpl0.toDBName("");
      assertNotNull(string0);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test005()  throws Throwable  {
      DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl();
      String string0 = dBIdentifierUtilImpl0.shorten((String) null, 5);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test006()  throws Throwable  {
      EmpressDictionary empressDictionary0 = new EmpressDictionary();
      DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(empressDictionary0);
      String string0 = dBIdentifierUtilImpl0.shorten("REF", 28);
      assertEquals("REF", string0);
  }

  @Test(timeout = 4000)
  public void test007()  throws Throwable  {
      DefaultIdentifierConfiguration defaultIdentifierConfiguration0 = new DefaultIdentifierConfiguration();
      DynamicSchemaFactory dynamicSchemaFactory0 = new DynamicSchemaFactory();
      DBIdentifier.DBIdentifierType dBIdentifier_DBIdentifierType0 = DBIdentifier.DBIdentifierType.COLUMN;
      DBIdentifier dBIdentifier0 = DBIdentifier.newIdentifier("preserve", dBIdentifier_DBIdentifierType0, true, true, true);
      DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(defaultIdentifierConfiguration0);
      DBIdentifier dBIdentifier1 = dBIdentifierUtilImpl0.makeIdentifierValid(dBIdentifier0, dynamicSchemaFactory0, (-1066), false);
      assertSame(dBIdentifier1, dBIdentifier0);
  }

  @Test(timeout = 4000)
  public void test008()  throws Throwable  {
      MySQLDictionary mySQLDictionary0 = new MySQLDictionary();
      DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(mySQLDictionary0);
      Table table0 = new Table();
      DBIdentifier dBIdentifier0 = dBIdentifierUtilImpl0.getValidUniqueIdentifier((DBIdentifier) null, table0, 255);
      assertNull(dBIdentifier0);
  }

  @Test(timeout = 4000)
  public void test009()  throws Throwable  {
      AccessDictionary accessDictionary0 = new AccessDictionary();
      DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(accessDictionary0);
      MappingDefaultsImpl mappingDefaultsImpl0 = new MappingDefaultsImpl();
      DBIdentifier dBIdentifier0 = mappingDefaultsImpl0.getDataStoreIdColumnIdentifier();
      LazySchemaFactory lazySchemaFactory0 = new LazySchemaFactory();
      Schema schema0 = lazySchemaFactory0.addSchema(dBIdentifier0);
      DBIdentifier dBIdentifier1 = dBIdentifierUtilImpl0.getValidTableIdentifier(dBIdentifier0, schema0, 0);
      assertFalse(dBIdentifier1.getIgnoreCase());
  }

  @Test(timeout = 4000)
  public void test010()  throws Throwable  {
      DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl();
      DBIdentifier dBIdentifier0 = dBIdentifierUtilImpl0.getValidSequenceIdentifier((DBIdentifier) null, (Schema) null, (-1617255209));
      assertNull(dBIdentifier0);
  }

  @Test(timeout = 4000)
  public void test011()  throws Throwable  {
      DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl();
      DBIdentifier dBIdentifier0 = dBIdentifierUtilImpl0.getValidIndexIdentifier((DBIdentifier) null, (Table) null, (-246));
      assertNull(dBIdentifier0);
  }

  @Test(timeout = 4000)
  public void test012()  throws Throwable  {
      DefaultIdentifierConfiguration defaultIdentifierConfiguration0 = new DefaultIdentifierConfiguration();
      DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(defaultIdentifierConfiguration0);
      DynamicSchemaFactory dynamicSchemaFactory0 = new DynamicSchemaFactory();
      DBIdentifier.DBIdentifierType dBIdentifier_DBIdentifierType0 = DBIdentifier.DBIdentifierType.SEQUENCE;
      DBIdentifier dBIdentifier0 = DBIdentifier.newIdentifier("_XWM[(g:", dBIdentifier_DBIdentifierType0, false, true, false);
      Schema schema0 = new Schema(dBIdentifier0, dynamicSchemaFactory0);
      Table table0 = schema0.addTable(dBIdentifier0);
      DBIdentifier dBIdentifier1 = dBIdentifierUtilImpl0.getValidIndexIdentifier(dBIdentifier0, table0, (-1));
      assertNotSame(dBIdentifier1, dBIdentifier0);
  }

  @Test(timeout = 4000)
  public void test013()  throws Throwable  {
      DefaultIdentifierConfiguration defaultIdentifierConfiguration0 = new DefaultIdentifierConfiguration();
      DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(defaultIdentifierConfiguration0);
      DBIdentifier dBIdentifier0 = DBIdentifier.newConstraint("EXTRACT({0} FROM {1})");
      SchemaGroup schemaGroup0 = new SchemaGroup();
      Schema schema0 = schemaGroup0.addSchema();
      Table table0 = schema0.addTable(dBIdentifier0);
      DBIdentifier dBIdentifier1 = dBIdentifierUtilImpl0.getValidForeignKeyIdentifier(dBIdentifier0, table0, table0, (-1));
      assertEquals(DBIdentifier.DBIdentifierType.CONSTRAINT, dBIdentifier1.getType());
  }

  @Test(timeout = 4000)
  public void test014()  throws Throwable  {
      DBIdentifier.DBIdentifierType dBIdentifier_DBIdentifierType0 = DBIdentifier.DBIdentifierType.COLUMN;
      DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl();
      DBIdentifier[] dBIdentifierArray0 = new DBIdentifier[0];
      DBIdentifier dBIdentifier0 = dBIdentifierUtilImpl0.append(dBIdentifier_DBIdentifierType0, dBIdentifierArray0);
      DBIdentifier dBIdentifier1 = dBIdentifierUtilImpl0.getValidForeignKeyIdentifier(dBIdentifier0, (Table) null, (Table) null, 3);
      assertSame(dBIdentifier1, dBIdentifier0);
  }

  @Test(timeout = 4000)
  public void test015()  throws Throwable  {
      FoxProDictionary foxProDictionary0 = new FoxProDictionary();
      DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(foxProDictionary0);
      Table table0 = new Table();
      DBIdentifier dBIdentifier0 = dBIdentifierUtilImpl0.getValidColumnIdentifier((DBIdentifier) null, table0, 1000000, true);
      assertNull(dBIdentifier0);
  }

  @Test(timeout = 4000)
  public void test016()  throws Throwable  {
      DBIdentifier dBIdentifier0 = DBIdentifier.newColumn("T0hp(V+(3%)2\"h,M}");
      DefaultIdentifierConfiguration defaultIdentifierConfiguration0 = new DefaultIdentifierConfiguration();
      DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(defaultIdentifierConfiguration0);
      DBIdentifier dBIdentifier1 = dBIdentifierUtilImpl0.getValidColumnIdentifier(dBIdentifier0, (Table) null, 7, false);
      assertFalse(dBIdentifier1.equals((Object)dBIdentifier0));
  }

  @Test(timeout = 4000)
  public void test017()  throws Throwable  {
      DefaultIdentifierConfiguration defaultIdentifierConfiguration0 = new DefaultIdentifierConfiguration();
      DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(defaultIdentifierConfiguration0);
      MappingDefaultsImpl mappingDefaultsImpl0 = new MappingDefaultsImpl();
      DBIdentifier dBIdentifier0 = mappingDefaultsImpl0.getDiscriminatorColumnIdentifier();
      String string0 = dBIdentifierUtilImpl0.delimit(dBIdentifier0, false);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test018()  throws Throwable  {
      DBIdentifier dBIdentifier0 = DBIdentifier.newTable("");
      DefaultIdentifierConfiguration defaultIdentifierConfiguration0 = new DefaultIdentifierConfiguration();
      DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(defaultIdentifierConfiguration0);
      String string0 = dBIdentifierUtilImpl0.delimit(dBIdentifier0, false);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test019()  throws Throwable  {
      DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl();
      String string0 = dBIdentifierUtilImpl0.convertAlias((String) null);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test020()  throws Throwable  {
      DefaultIdentifierConfiguration defaultIdentifierConfiguration0 = new DefaultIdentifierConfiguration();
      DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(defaultIdentifierConfiguration0);
      String string0 = dBIdentifierUtilImpl0.convertAlias("");
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test021()  throws Throwable  {
      JDataStoreDictionary jDataStoreDictionary0 = new JDataStoreDictionary();
      DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(jDataStoreDictionary0);
      Column[] columnArray0 = new Column[1];
      Column column0 = new Column();
      columnArray0[0] = column0;
      String string0 = dBIdentifierUtilImpl0.appendColumns(columnArray0);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test022()  throws Throwable  {
      HerdDBDictionary herdDBDictionary0 = new HerdDBDictionary();
      DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(herdDBDictionary0);
      // Undeclared exception!
      dBIdentifierUtilImpl0.shorten(".", (-1));
  }

  @Test(timeout = 4000)
  public void test023()  throws Throwable  {
      DefaultIdentifierConfiguration defaultIdentifierConfiguration0 = new DefaultIdentifierConfiguration();
      DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(defaultIdentifierConfiguration0);
      LazySchemaFactory lazySchemaFactory0 = new LazySchemaFactory();
      // Undeclared exception!
      try { 
        dBIdentifierUtilImpl0.makeNameValid("MEMO", lazySchemaFactory0, 0, 1, true);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.openjpa.jdbc.schema.LazySchemaFactory", e);
      }
  }

  @Test(timeout = 4000)
  public void test024()  throws Throwable  {
      DBIdentifier dBIdentifier0 = DBIdentifier.newTable("LEFT OUTER JOIN");
      DynamicSchemaFactory dynamicSchemaFactory0 = new DynamicSchemaFactory();
      DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl();
      // Undeclared exception!
      try { 
        dBIdentifierUtilImpl0.makeIdentifierValid(dBIdentifier0, dynamicSchemaFactory0, 0, false);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.openjpa.jdbc.identifier.DBIdentifierUtilImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test025()  throws Throwable  {
      DBIdentifier dBIdentifier0 = DBIdentifier.newTable("INTEGER");
      DefaultIdentifierConfiguration defaultIdentifierConfiguration0 = new DefaultIdentifierConfiguration();
      DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(defaultIdentifierConfiguration0);
      LazySchemaFactory lazySchemaFactory0 = new LazySchemaFactory();
      // Undeclared exception!
      try { 
        dBIdentifierUtilImpl0.makeIdentifierValid(dBIdentifier0, lazySchemaFactory0, 255, true);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.openjpa.jdbc.schema.LazySchemaFactory", e);
      }
  }

  @Test(timeout = 4000)
  public void test026()  throws Throwable  {
      HerdDBDictionary herdDBDictionary0 = new HerdDBDictionary();
      DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(herdDBDictionary0);
      DynamicSchemaFactory dynamicSchemaFactory0 = new DynamicSchemaFactory();
      DBIdentifier dBIdentifier0 = DBIdentifier.newIndex("DISTINCT");
      // Undeclared exception!
      try { 
        dBIdentifierUtilImpl0.makeIdentifierValid(dBIdentifier0, dynamicSchemaFactory0, 255, true);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Naming rule is null!
         //
         verifyException("org.apache.openjpa.lib.identifier.IdentifierUtilImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test027()  throws Throwable  {
      DBIdentifier dBIdentifier0 = DBIdentifier.newTable("BIGINT");
      DefaultIdentifierConfiguration defaultIdentifierConfiguration0 = new DefaultIdentifierConfiguration();
      DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(defaultIdentifierConfiguration0);
      Table table0 = new Table();
      // Undeclared exception!
      try { 
        dBIdentifierUtilImpl0.makeIdentifierValid(dBIdentifier0, table0, 3, true);
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // class org.apache.openjpa.jdbc.schema.Table cannot be cast to class org.apache.openjpa.jdbc.schema.SchemaGroup (org.apache.openjpa.jdbc.schema.Table and org.apache.openjpa.jdbc.schema.SchemaGroup are in unnamed module of loader org.evosuite.instrumentation.InstrumentingClassLoader @42c45a39)
         //
         verifyException("org.apache.openjpa.jdbc.identifier.DBIdentifierUtilImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test028()  throws Throwable  {
      DefaultIdentifierConfiguration defaultIdentifierConfiguration0 = new DefaultIdentifierConfiguration();
      DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(defaultIdentifierConfiguration0);
      LazySchemaFactory lazySchemaFactory0 = new LazySchemaFactory();
      DBIdentifier dBIdentifier0 = DBIdentifier.newSequence("T0hp(V+(3%)2\"h,M}", false);
      Schema schema0 = lazySchemaFactory0.addSchema();
      Table table0 = schema0.addTable(dBIdentifier0);
      // Undeclared exception!
      try { 
        dBIdentifierUtilImpl0.getValidUniqueIdentifier(dBIdentifier0, table0, (-2394));
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.openjpa.jdbc.schema.LazySchemaFactory", e);
      }
  }

  @Test(timeout = 4000)
  public void test029()  throws Throwable  {
      FoxProDictionary foxProDictionary0 = new FoxProDictionary();
      DBIdentifier dBIdentifier0 = DBIdentifier.newTable("TIMESTAMP");
      DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(foxProDictionary0);
      Schema schema0 = new Schema();
      Table table0 = new Table(dBIdentifier0, schema0);
      // Undeclared exception!
      try { 
        dBIdentifierUtilImpl0.getValidUniqueIdentifier(dBIdentifier0, table0, 30);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Naming rule is null!
         //
         verifyException("org.apache.openjpa.lib.identifier.IdentifierUtilImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test030()  throws Throwable  {
      FoxProDictionary foxProDictionary0 = new FoxProDictionary();
      DBIdentifier dBIdentifier0 = DBIdentifier.newTable("({0}||{1})");
      DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(foxProDictionary0);
      // Undeclared exception!
      try { 
        dBIdentifierUtilImpl0.getValidTableIdentifier(dBIdentifier0, (Schema) null, 8);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.openjpa.jdbc.identifier.DBIdentifierUtilImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test031()  throws Throwable  {
      DBIdentifier dBIdentifier0 = DBIdentifier.newTable("INTEGER");
      DefaultIdentifierConfiguration defaultIdentifierConfiguration0 = new DefaultIdentifierConfiguration();
      DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(defaultIdentifierConfiguration0);
      LazySchemaFactory lazySchemaFactory0 = new LazySchemaFactory();
      Schema schema0 = lazySchemaFactory0.addSchema(dBIdentifier0);
      // Undeclared exception!
      try { 
        dBIdentifierUtilImpl0.getValidTableIdentifier(dBIdentifier0, schema0, 675);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.openjpa.jdbc.schema.LazySchemaFactory", e);
      }
  }

  @Test(timeout = 4000)
  public void test032()  throws Throwable  {
      FoxProDictionary foxProDictionary0 = new FoxProDictionary();
      Schema schema0 = new Schema();
      DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(foxProDictionary0);
      DBIdentifier dBIdentifier0 = DBIdentifier.newIndex("INTEGER");
      // Undeclared exception!
      try { 
        dBIdentifierUtilImpl0.getValidSequenceIdentifier(dBIdentifier0, schema0, 1);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Naming rule is null!
         //
         verifyException("org.apache.openjpa.lib.identifier.IdentifierUtilImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test033()  throws Throwable  {
      SolidDBDictionary solidDBDictionary0 = new SolidDBDictionary();
      DBIdentifier dBIdentifier0 = DBIdentifier.newTable("upper");
      DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(solidDBDictionary0);
      Schema schema0 = new Schema(dBIdentifier0, (SchemaGroup) null);
      Table table0 = schema0.addTable(dBIdentifier0);
      // Undeclared exception!
      try { 
        dBIdentifierUtilImpl0.getValidIndexIdentifier(dBIdentifier0, table0, 31);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Naming rule is null!
         //
         verifyException("org.apache.openjpa.lib.identifier.IdentifierUtilImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test034()  throws Throwable  {
      SolidDBDictionary solidDBDictionary0 = new SolidDBDictionary();
      DBIdentifier dBIdentifier0 = DBIdentifier.newTable("INTEGER");
      DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(solidDBDictionary0);
      Schema schema0 = new Schema();
      Table table0 = schema0.addTable(dBIdentifier0);
      // Undeclared exception!
      try { 
        dBIdentifierUtilImpl0.getValidForeignKeyIdentifier(dBIdentifier0, table0, table0, 0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.openjpa.jdbc.identifier.DBIdentifierUtilImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test035()  throws Throwable  {
      DBIdentifier dBIdentifier0 = DBIdentifier.newTable("SELECT current_database() AS \"TABLE_CAT\",  n.nspname AS \"TABLE_SCHEM\", ");
      DefaultIdentifierConfiguration defaultIdentifierConfiguration0 = new DefaultIdentifierConfiguration();
      DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(defaultIdentifierConfiguration0);
      LazySchemaFactory lazySchemaFactory0 = new LazySchemaFactory();
      Schema schema0 = lazySchemaFactory0.addSchema(dBIdentifier0);
      Table table0 = schema0.addTable(dBIdentifier0);
      // Undeclared exception!
      try { 
        dBIdentifierUtilImpl0.getValidForeignKeyIdentifier(dBIdentifier0, table0, table0, (-28));
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.openjpa.jdbc.schema.LazySchemaFactory", e);
      }
  }

  @Test(timeout = 4000)
  public void test036()  throws Throwable  {
      SolidDBDictionary solidDBDictionary0 = new SolidDBDictionary();
      DBIdentifier dBIdentifier0 = DBIdentifier.newTable("INTEGER");
      DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(solidDBDictionary0);
      Schema schema0 = new Schema();
      Table table0 = schema0.addTable(dBIdentifier0);
      // Undeclared exception!
      try { 
        dBIdentifierUtilImpl0.getValidForeignKeyIdentifier(dBIdentifier0, table0, table0, 6);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Naming rule is null!
         //
         verifyException("org.apache.openjpa.lib.identifier.IdentifierUtilImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test037()  throws Throwable  {
      SolidDBDictionary solidDBDictionary0 = new SolidDBDictionary();
      DBIdentifier dBIdentifier0 = DBIdentifier.newTable("INTEGER");
      Schema schema0 = new Schema();
      Table table0 = schema0.addTable(dBIdentifier0);
      DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(solidDBDictionary0);
      // Undeclared exception!
      try { 
        dBIdentifierUtilImpl0.getValidColumnIdentifier(dBIdentifier0, table0, 128, false);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Naming rule is null!
         //
         verifyException("org.apache.openjpa.lib.identifier.IdentifierUtilImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test038()  throws Throwable  {
      DefaultIdentifierConfiguration defaultIdentifierConfiguration0 = new DefaultIdentifierConfiguration();
      DBIdentifier dBIdentifier0 = DBIdentifier.newTable("SMALLINT");
      DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(defaultIdentifierConfiguration0);
      Table table0 = new Table();
      // Undeclared exception!
      try { 
        dBIdentifierUtilImpl0.getValidColumnIdentifier(dBIdentifier0, table0, (byte)68, true);
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // class org.apache.openjpa.jdbc.schema.Table cannot be cast to class org.apache.openjpa.jdbc.schema.SchemaGroup (org.apache.openjpa.jdbc.schema.Table and org.apache.openjpa.jdbc.schema.SchemaGroup are in unnamed module of loader org.evosuite.instrumentation.InstrumentingClassLoader @42c45a39)
         //
         verifyException("org.apache.openjpa.jdbc.identifier.DBIdentifierUtilImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test039()  throws Throwable  {
      Column column0 = new Column();
      DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl();
      // Undeclared exception!
      try { 
        dBIdentifierUtilImpl0.getGeneratedKeySequenceName(column0, 128);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.openjpa.jdbc.identifier.DBIdentifierUtilImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test040()  throws Throwable  {
      DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl();
      DBIdentifier.DBIdentifierType dBIdentifier_DBIdentifierType0 = DBIdentifier.DBIdentifierType.SEQUENCE;
      // Undeclared exception!
      try { 
        dBIdentifierUtilImpl0.fromDBName("59,IE#R0YMyME{i@9", dBIdentifier_DBIdentifierType0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.openjpa.jdbc.identifier.DBIdentifierUtilImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test041()  throws Throwable  {
      HerdDBDictionary herdDBDictionary0 = new HerdDBDictionary();
      DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(herdDBDictionary0);
      DBIdentifier.DBIdentifierType dBIdentifier_DBIdentifierType0 = DBIdentifier.DBIdentifierType.NULL;
      // Undeclared exception!
      try { 
        dBIdentifierUtilImpl0.fromDBName("STRUCT", dBIdentifier_DBIdentifierType0);
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Cannot modify NULL instance
         //
         verifyException("org.apache.openjpa.jdbc.identifier.DBIdentifier", e);
      }
  }

  @Test(timeout = 4000)
  public void test042()  throws Throwable  {
      DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl();
      DBIdentifier dBIdentifier0 = new DBIdentifier();
      // Undeclared exception!
      try { 
        dBIdentifierUtilImpl0.convertSchemaCase(dBIdentifier0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.openjpa.jdbc.identifier.DBIdentifierUtilImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test043()  throws Throwable  {
      DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl();
      DBIdentifier.DBIdentifierType dBIdentifier_DBIdentifierType0 = DBIdentifier.DBIdentifierType.NULL;
      DBIdentifier[] dBIdentifierArray0 = new DBIdentifier[3];
      // Undeclared exception!
      try { 
        dBIdentifierUtilImpl0.append(dBIdentifier_DBIdentifierType0, dBIdentifierArray0);
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Cannot modify NULL instance
         //
         verifyException("org.apache.openjpa.jdbc.identifier.DBIdentifier", e);
      }
  }

  @Test(timeout = 4000)
  public void test044()  throws Throwable  {
      DBIdentifier dBIdentifier0 = DBIdentifier.newColumn("T0hp(V+(3%)2\"h,M}");
      DefaultIdentifierConfiguration defaultIdentifierConfiguration0 = new DefaultIdentifierConfiguration();
      DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(defaultIdentifierConfiguration0);
      LazySchemaFactory lazySchemaFactory0 = new LazySchemaFactory();
      Schema schema0 = new Schema(dBIdentifier0, lazySchemaFactory0);
      Table table0 = schema0.addTable(dBIdentifier0, dBIdentifier0);
      Column column0 = table0.addColumn(dBIdentifier0);
      // Undeclared exception!
      try { 
        dBIdentifierUtilImpl0.getGeneratedKeySequenceName(column0, (-34811809));
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test045()  throws Throwable  {
      DBIdentifier dBIdentifier0 = DBIdentifier.newTable("INTEGER");
      DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl();
      // Undeclared exception!
      try { 
        dBIdentifierUtilImpl0.delimit(dBIdentifier0, true);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.openjpa.lib.identifier.IdentifierUtilImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test046()  throws Throwable  {
      DBIdentifier dBIdentifier0 = DBIdentifier.newCatalog(" <)W8]e,c`1>E~f?)%1");
      DefaultIdentifierConfiguration defaultIdentifierConfiguration0 = new DefaultIdentifierConfiguration();
      DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(defaultIdentifierConfiguration0);
      String string0 = dBIdentifierUtilImpl0.toDBName(dBIdentifier0, true);
      assertEquals("\" <)W8]e,c`1>E~f?)%1\"", string0);
  }

  @Test(timeout = 4000)
  public void test047()  throws Throwable  {
      HerdDBDictionary herdDBDictionary0 = new HerdDBDictionary();
      DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(herdDBDictionary0);
      DBIdentifier.DBIdentifierType dBIdentifier_DBIdentifierType0 = DBIdentifier.DBIdentifierType.COLUMN_DEFINITION;
      DBIdentifier dBIdentifier0 = dBIdentifierUtilImpl0.fromDBName("SUBSTRING", dBIdentifier_DBIdentifierType0);
      // Undeclared exception!
      try { 
        dBIdentifierUtilImpl0.toDBName(dBIdentifier0, true);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.openjpa.lib.identifier.IdentifierUtilImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test048()  throws Throwable  {
      DefaultIdentifierConfiguration defaultIdentifierConfiguration0 = new DefaultIdentifierConfiguration();
      DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(defaultIdentifierConfiguration0);
      String string0 = dBIdentifierUtilImpl0.toDBName((DBIdentifier) null, false);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test049()  throws Throwable  {
      DefaultIdentifierConfiguration defaultIdentifierConfiguration0 = new DefaultIdentifierConfiguration();
      DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(defaultIdentifierConfiguration0);
      DBIdentifier dBIdentifier0 = DBIdentifier.newConstraint("EXTRACT({0} FROM {1})");
      DynamicSchemaFactory dynamicSchemaFactory0 = new DynamicSchemaFactory();
      DBIdentifier dBIdentifier1 = dBIdentifierUtilImpl0.makeIdentifierValid(dBIdentifier0, dynamicSchemaFactory0, 6, false);
      assertFalse(dBIdentifier1.equals((Object)dBIdentifier0));
      assertNotSame(dBIdentifier1, dBIdentifier0);
  }

  @Test(timeout = 4000)
  public void test050()  throws Throwable  {
      DefaultIdentifierConfiguration defaultIdentifierConfiguration0 = new DefaultIdentifierConfiguration();
      DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(defaultIdentifierConfiguration0);
      DBIdentifier dBIdentifier0 = DBIdentifier.newConstraint("EXTRACT({0} FROM {1})");
      DBIdentifier dBIdentifier1 = dBIdentifierUtilImpl0.makeIdentifierValid(dBIdentifier0, (NameSet) null, 1372, false);
      assertSame(dBIdentifier1, dBIdentifier0);
  }

  @Test(timeout = 4000)
  public void test051()  throws Throwable  {
      SolidDBDictionary solidDBDictionary0 = new SolidDBDictionary();
      DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(solidDBDictionary0);
      String string0 = dBIdentifierUtilImpl0.convertAlias("before");
      assertEquals("before", string0);
  }

  @Test(timeout = 4000)
  public void test052()  throws Throwable  {
      EmpressDictionary empressDictionary0 = new EmpressDictionary();
      DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(empressDictionary0);
      DBIdentifier dBIdentifier0 = DBIdentifier.newSequence("after");
      DBIdentifier dBIdentifier1 = dBIdentifierUtilImpl0.convertSchemaCase(dBIdentifier0);
      assertNotSame(dBIdentifier1, dBIdentifier0);
  }

  @Test(timeout = 4000)
  public void test053()  throws Throwable  {
      DBIdentifier dBIdentifier0 = DBIdentifier.newTable("XML");
      PostgresDictionary postgresDictionary0 = new PostgresDictionary();
      DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(postgresDictionary0);
      DBIdentifier dBIdentifier1 = dBIdentifierUtilImpl0.convertSchemaCase(dBIdentifier0);
      assertNotSame(dBIdentifier1, dBIdentifier0);
  }

  @Test(timeout = 4000)
  public void test054()  throws Throwable  {
      SolidDBDictionary solidDBDictionary0 = new SolidDBDictionary();
      DBIdentifier dBIdentifier0 = DBIdentifier.newTable("INTEGER");
      DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(solidDBDictionary0);
      DBIdentifier dBIdentifier1 = dBIdentifierUtilImpl0.convertSchemaCase(dBIdentifier0);
      assertNotSame(dBIdentifier0, dBIdentifier1);
  }

  @Test(timeout = 4000)
  public void test055()  throws Throwable  {
      HerdDBDictionary herdDBDictionary0 = new HerdDBDictionary();
      DBIdentifier dBIdentifier0 = DBIdentifier.newTable("LEFT OUTER JOIN");
      DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(herdDBDictionary0);
      DBIdentifier dBIdentifier1 = dBIdentifierUtilImpl0.convertSchemaCase(dBIdentifier0);
      assertFalse(dBIdentifier1.equals((Object)dBIdentifier0));
  }

  @Test(timeout = 4000)
  public void test056()  throws Throwable  {
      HerdDBDictionary herdDBDictionary0 = new HerdDBDictionary();
      DBIdentifier dBIdentifier0 = DBIdentifier.newTable("_");
      DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(herdDBDictionary0);
      DBIdentifier dBIdentifier1 = dBIdentifierUtilImpl0.convertSchemaCase(dBIdentifier0);
      assertNotSame(dBIdentifier1, dBIdentifier0);
  }

  @Test(timeout = 4000)
  public void test057()  throws Throwable  {
      DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl();
      MappingDefaultsImpl mappingDefaultsImpl0 = new MappingDefaultsImpl();
      DBIdentifier dBIdentifier0 = mappingDefaultsImpl0.getVersionColumnIdentifier();
      DBIdentifier dBIdentifier1 = dBIdentifierUtilImpl0.convertSchemaCase(dBIdentifier0);
      assertSame(dBIdentifier0, dBIdentifier1);
  }

  @Test(timeout = 4000)
  public void test058()  throws Throwable  {
      SolidDBDictionary solidDBDictionary0 = new SolidDBDictionary();
      DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(solidDBDictionary0);
      DBIdentifier dBIdentifier0 = DBIdentifier.newTable("W<^#U~xXsrkBO");
      DBIdentifier dBIdentifier1 = dBIdentifierUtilImpl0.convertSchemaCase(dBIdentifier0);
      assertFalse(dBIdentifier1.equals((Object)dBIdentifier0));
  }

  @Test(timeout = 4000)
  public void test059()  throws Throwable  {
      SolidDBDictionary solidDBDictionary0 = new SolidDBDictionary();
      DBIdentifier dBIdentifier0 = DBIdentifier.newTable("INTEGER");
      Schema schema0 = new Schema();
      Table table0 = schema0.addTable(dBIdentifier0);
      DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(solidDBDictionary0);
      Column column0 = table0.addColumn(dBIdentifier0, dBIdentifier0);
      DBIdentifier dBIdentifier1 = dBIdentifierUtilImpl0.getGeneratedKeySequenceName(column0, 128);
      assertFalse(dBIdentifier1.isNameDelimited());
  }

  @Test(timeout = 4000)
  public void test060()  throws Throwable  {
      DBIdentifier dBIdentifier0 = DBIdentifier.newTable("SELECT {0}.CURRENT");
      DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl();
      // Undeclared exception!
      try { 
        dBIdentifierUtilImpl0.delimit(dBIdentifier0, false);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.openjpa.lib.identifier.IdentifierUtilImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test061()  throws Throwable  {
      DBIdentifier dBIdentifier0 = DBIdentifier.newTable("SELECT current_database() AS \"TABLE_CAT\",  n.nspname AS \"TABLE_SCHEM\", ");
      DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl();
      String string0 = dBIdentifierUtilImpl0.delimit(dBIdentifier0, false);
      assertEquals("\"SELECT current_database() AS \"TABLE_CAT\",  n\".\"nspname AS \"TABLE_SCHEM\", \"", string0);
  }

  @Test(timeout = 4000)
  public void test062()  throws Throwable  {
      DBIdentifier dBIdentifier0 = DBIdentifier.newColumn("SELECT current_database() AS \"TABLE_CAT\",  n.nspname AS \"TABLE_SCHEM\", ");
      CacheDictionary cacheDictionary0 = new CacheDictionary();
      DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(cacheDictionary0);
      String string0 = dBIdentifierUtilImpl0.delimit(dBIdentifier0, true);
      assertEquals("\"SELECT current_database() AS \"TABLE_CAT\",  n\".\"nspname AS \"TABLE_SCHEM\", \"", string0);
  }

  @Test(timeout = 4000)
  public void test063()  throws Throwable  {
      FoxProDictionary foxProDictionary0 = new FoxProDictionary();
      DBIdentifier dBIdentifier0 = DBIdentifier.newColumn("_");
      DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(foxProDictionary0);
      // Undeclared exception!
      try { 
        dBIdentifierUtilImpl0.delimit(dBIdentifier0, true);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.openjpa.lib.identifier.IdentifierUtilImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test064()  throws Throwable  {
      DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl();
      Column column0 = new Column();
      Column[] columnArray0 = new Column[2];
      columnArray0[0] = column0;
      columnArray0[1] = column0;
      String string0 = dBIdentifierUtilImpl0.appendColumns(columnArray0);
      assertNotNull(string0);
      assertEquals("null, null", string0);
  }

  @Test(timeout = 4000)
  public void test065()  throws Throwable  {
      DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl();
      Column[] columnArray0 = new Column[2];
      // Undeclared exception!
      try { 
        dBIdentifierUtilImpl0.appendColumns(columnArray0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.openjpa.jdbc.identifier.DBIdentifierUtilImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test066()  throws Throwable  {
      DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl();
      Column[] columnArray0 = new Column[0];
      String string0 = dBIdentifierUtilImpl0.appendColumns(columnArray0);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test067()  throws Throwable  {
      DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl();
      String string0 = dBIdentifierUtilImpl0.appendColumns((Column[]) null);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test068()  throws Throwable  {
      DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl();
      MappingDefaultsImpl mappingDefaultsImpl0 = new MappingDefaultsImpl();
      DBIdentifier dBIdentifier0 = mappingDefaultsImpl0.getVersionColumnIdentifier();
      DBIdentifier.DBIdentifierType dBIdentifier_DBIdentifierType0 = DBIdentifier.DBIdentifierType.CONSTANT;
      DBIdentifier[] dBIdentifierArray0 = new DBIdentifier[2];
      dBIdentifierArray0[0] = dBIdentifier0;
      dBIdentifierArray0[1] = dBIdentifier0;
      DBIdentifier dBIdentifier1 = dBIdentifierUtilImpl0.append(dBIdentifier_DBIdentifierType0, dBIdentifierArray0);
      assertEquals(DBIdentifier.DBIdentifierType.CONSTANT, dBIdentifier1.getType());
  }

  @Test(timeout = 4000)
  public void test069()  throws Throwable  {
      DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl();
      DBIdentifier.DBIdentifierType dBIdentifier_DBIdentifierType0 = DBIdentifier.DBIdentifierType.CONSTANT;
      DBIdentifier[] dBIdentifierArray0 = new DBIdentifier[2];
      // Undeclared exception!
      try { 
        dBIdentifierUtilImpl0.append(dBIdentifier_DBIdentifierType0, dBIdentifierArray0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.openjpa.jdbc.identifier.DBIdentifierUtilImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test070()  throws Throwable  {
      SolidDBDictionary solidDBDictionary0 = new SolidDBDictionary();
      DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(solidDBDictionary0);
      DBIdentifier.DBIdentifierType dBIdentifier_DBIdentifierType0 = DBIdentifier.DBIdentifierType.COLUMN_DEFINITION;
      DBIdentifier dBIdentifier0 = dBIdentifierUtilImpl0.append(dBIdentifier_DBIdentifierType0, (DBIdentifier[]) null);
      assertFalse(dBIdentifier0.getIgnoreCase());
  }

  @Test(timeout = 4000)
  public void test071()  throws Throwable  {
      DefaultIdentifierConfiguration defaultIdentifierConfiguration0 = new DefaultIdentifierConfiguration();
      DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(defaultIdentifierConfiguration0);
      DBIdentifier.DBIdentifierType dBIdentifier_DBIdentifierType0 = DBIdentifier.DBIdentifierType.FOREIGN_KEY;
      DBIdentifier dBIdentifier0 = dBIdentifierUtilImpl0.fromDBName("", dBIdentifier_DBIdentifierType0);
      assertFalse(dBIdentifier0._ignoreCase);
      assertFalse(dBIdentifier0.isNameDelimited());
  }

  @Test(timeout = 4000)
  public void test072()  throws Throwable  {
      DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl();
      DBIdentifier.DBIdentifierType dBIdentifier_DBIdentifierType0 = DBIdentifier.DBIdentifierType.COLUMN;
      DBIdentifier dBIdentifier0 = dBIdentifierUtilImpl0.fromDBName((String) null, dBIdentifier_DBIdentifierType0);
      assertFalse(dBIdentifier0.isNameDelimited());
  }

  @Test(timeout = 4000)
  public void test073()  throws Throwable  {
      DefaultIdentifierConfiguration defaultIdentifierConfiguration0 = new DefaultIdentifierConfiguration();
      DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(defaultIdentifierConfiguration0);
      String string0 = dBIdentifierUtilImpl0.toDBName("", false);
      assertNotNull(string0);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test074()  throws Throwable  {
      DefaultIdentifierConfiguration defaultIdentifierConfiguration0 = new DefaultIdentifierConfiguration();
      DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(defaultIdentifierConfiguration0);
      String string0 = dBIdentifierUtilImpl0.toDBName((String) null);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test075()  throws Throwable  {
      DefaultIdentifierConfiguration defaultIdentifierConfiguration0 = new DefaultIdentifierConfiguration();
      DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(defaultIdentifierConfiguration0);
      String string0 = dBIdentifierUtilImpl0.toDBName("C");
      assertEquals("C", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test076()  throws Throwable  {
      HerdDBDictionary herdDBDictionary0 = new HerdDBDictionary();
      DBIdentifier dBIdentifier0 = DBIdentifier.newTable("LEFT OUTER JOIN");
      DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(herdDBDictionary0);
      String string0 = dBIdentifierUtilImpl0.toDBName(dBIdentifier0, true);
      assertEquals("`LEFT OUTER JOIN`", string0);
  }

  @Test(timeout = 4000)
  public void test077()  throws Throwable  {
      HerdDBDictionary herdDBDictionary0 = new HerdDBDictionary();
      DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(herdDBDictionary0);
      DBIdentifier dBIdentifier0 = DBIdentifier.newTable("SMALLINT", false);
      // Undeclared exception!
      try { 
        dBIdentifierUtilImpl0.toDBName(dBIdentifier0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.openjpa.lib.identifier.IdentifierUtilImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test078()  throws Throwable  {
      DefaultIdentifierConfiguration defaultIdentifierConfiguration0 = new DefaultIdentifierConfiguration();
      DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(defaultIdentifierConfiguration0);
      DBIdentifier dBIdentifier0 = DBIdentifier.newTable("upper", false);
      String string0 = dBIdentifierUtilImpl0.toDBName(dBIdentifier0);
      assertEquals("upper", string0);
  }

  @Test(timeout = 4000)
  public void test079()  throws Throwable  {
      FoxProDictionary foxProDictionary0 = new FoxProDictionary();
      DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(foxProDictionary0);
      DBIdentifier.DBIdentifierType dBIdentifier_DBIdentifierType0 = DBIdentifier.DBIdentifierType.COLUMN_DEFINITION;
      DBIdentifier dBIdentifier0 = dBIdentifierUtilImpl0.fromDBName("", dBIdentifier_DBIdentifierType0);
      String string0 = dBIdentifierUtilImpl0.toDBName(dBIdentifier0, false);
      assertEquals("", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test080()  throws Throwable  {
      DBIdentifier dBIdentifier0 = DBIdentifier.newCatalog(" <)W8]e,c`1>E~f?)%1");
      DefaultIdentifierConfiguration defaultIdentifierConfiguration0 = new DefaultIdentifierConfiguration();
      DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(defaultIdentifierConfiguration0);
      String string0 = dBIdentifierUtilImpl0.toDBName(dBIdentifier0, false);
      assertEquals("\" <)W8]e,c`1>E~f?)%1\"", string0);
  }

  @Test(timeout = 4000)
  public void test081()  throws Throwable  {
      DBIdentifier dBIdentifier0 = DBIdentifier.newColumn("CHAR_LENGTH({0})");
      DefaultIdentifierConfiguration defaultIdentifierConfiguration0 = new DefaultIdentifierConfiguration();
      DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(defaultIdentifierConfiguration0);
      LazySchemaFactory lazySchemaFactory0 = new LazySchemaFactory();
      Schema schema0 = lazySchemaFactory0.addSchema(dBIdentifier0);
      DBIdentifier dBIdentifier1 = dBIdentifierUtilImpl0.getValidTableIdentifier(dBIdentifier0, schema0, 3);
      assertFalse(dBIdentifier1.equals((Object)dBIdentifier0));
  }

  @Test(timeout = 4000)
  public void test082()  throws Throwable  {
      DefaultIdentifierConfiguration defaultIdentifierConfiguration0 = new DefaultIdentifierConfiguration();
      DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(defaultIdentifierConfiguration0);
      DynamicSchemaFactory dynamicSchemaFactory0 = new DynamicSchemaFactory();
      DBIdentifier dBIdentifier0 = DBIdentifier.newColumn("");
      DBIdentifier dBIdentifier1 = dBIdentifierUtilImpl0.makeIdentifierValid(dBIdentifier0, dynamicSchemaFactory0, (-1), true);
      assertFalse(dBIdentifier1.equals((Object)dBIdentifier0));
  }

  @Test(timeout = 4000)
  public void test083()  throws Throwable  {
      DefaultIdentifierConfiguration defaultIdentifierConfiguration0 = new DefaultIdentifierConfiguration();
      DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(defaultIdentifierConfiguration0);
      DynamicSchemaFactory dynamicSchemaFactory0 = new DynamicSchemaFactory();
      DBIdentifier.DBIdentifierType dBIdentifier_DBIdentifierType0 = DBIdentifier.DBIdentifierType.SEQUENCE;
      DBIdentifier dBIdentifier0 = DBIdentifier.newIdentifier("_XWM[(g:", dBIdentifier_DBIdentifierType0, false, true, false);
      DBIdentifier dBIdentifier1 = dBIdentifierUtilImpl0.makeIdentifierValid(dBIdentifier0, dynamicSchemaFactory0, 1, true);
      assertTrue(dBIdentifier1.equals((Object)dBIdentifier0));
      assertNotSame(dBIdentifier1, dBIdentifier0);
  }

  @Test(timeout = 4000)
  public void test084()  throws Throwable  {
      DBIdentifier dBIdentifier0 = DBIdentifier.newTable("INTEGER");
      DefaultIdentifierConfiguration defaultIdentifierConfiguration0 = new DefaultIdentifierConfiguration();
      DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(defaultIdentifierConfiguration0);
      DynamicSchemaFactory dynamicSchemaFactory0 = new DynamicSchemaFactory();
      DBIdentifier dBIdentifier1 = dBIdentifierUtilImpl0.makeIdentifierValid(dBIdentifier0, dynamicSchemaFactory0, 255, true);
      assertTrue(dBIdentifier1.equals((Object)dBIdentifier0));
  }

  @Test(timeout = 4000)
  public void test085()  throws Throwable  {
      DefaultIdentifierConfiguration defaultIdentifierConfiguration0 = new DefaultIdentifierConfiguration();
      DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(defaultIdentifierConfiguration0);
      SchemaGroup schemaGroup0 = new SchemaGroup();
      DBIdentifier dBIdentifier0 = dBIdentifierUtilImpl0.makeNameValid("lower", schemaGroup0, 5, (-2394), false);
      assertFalse(dBIdentifier0._ignoreCase);
  }

  @Test(timeout = 4000)
  public void test086()  throws Throwable  {
      FoxProDictionary foxProDictionary0 = new FoxProDictionary();
      Table table0 = new Table();
      DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(foxProDictionary0);
      // Undeclared exception!
      try { 
        dBIdentifierUtilImpl0.makeNameValid("TRIM(TRAILING {1} FROM {0})", table0, 0, 3, true);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.openjpa.jdbc.identifier.DBIdentifierUtilImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test087()  throws Throwable  {
      IngresDictionary ingresDictionary0 = new IngresDictionary();
      DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(ingresDictionary0);
      NameSet nameSet0 = new NameSet();
      // Undeclared exception!
      try { 
        dBIdentifierUtilImpl0.makeNameValid("LONG BYTE", nameSet0, 6, 2, true);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Naming rule is null!
         //
         verifyException("org.apache.openjpa.lib.identifier.IdentifierUtilImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test088()  throws Throwable  {
      DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl();
      LazySchemaFactory lazySchemaFactory0 = new LazySchemaFactory();
      Schema schema0 = lazySchemaFactory0.addSchema((DBIdentifier) null);
      DBIdentifier dBIdentifier0 = dBIdentifierUtilImpl0.getValidTableIdentifier((DBIdentifier) null, schema0, 4017);
      assertNull(dBIdentifier0);
  }

  @Test(timeout = 4000)
  public void test089()  throws Throwable  {
      SolidDBDictionary solidDBDictionary0 = new SolidDBDictionary();
      DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(solidDBDictionary0);
      DBIdentifier dBIdentifier0 = DBIdentifier.newTable("W<^#U~xXsrkBO");
      SchemaGroup schemaGroup0 = new SchemaGroup();
      Schema schema0 = schemaGroup0.addSchema();
      // Undeclared exception!
      try { 
        dBIdentifierUtilImpl0.getValidTableIdentifier(dBIdentifier0, schema0, 1030);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Naming rule is null!
         //
         verifyException("org.apache.openjpa.lib.identifier.IdentifierUtilImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test090()  throws Throwable  {
      DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl();
      MappingDefaultsImpl mappingDefaultsImpl0 = new MappingDefaultsImpl();
      DBIdentifier dBIdentifier0 = mappingDefaultsImpl0.getVersionColumnIdentifier();
      LazySchemaFactory lazySchemaFactory0 = new LazySchemaFactory();
      Schema schema0 = lazySchemaFactory0.addSchema();
      DBIdentifier dBIdentifier1 = dBIdentifierUtilImpl0.getValidSequenceIdentifier(dBIdentifier0, schema0, 1604);
      assertSame(dBIdentifier1, dBIdentifier0);
  }

  @Test(timeout = 4000)
  public void test091()  throws Throwable  {
      SolidDBDictionary solidDBDictionary0 = new SolidDBDictionary();
      DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(solidDBDictionary0);
      DBIdentifier dBIdentifier0 = DBIdentifier.newTable("STRUCT");
      SchemaGroup schemaGroup0 = new SchemaGroup();
      Schema schema0 = schemaGroup0.getSchema(dBIdentifier0);
      // Undeclared exception!
      try { 
        dBIdentifierUtilImpl0.getValidSequenceIdentifier(dBIdentifier0, schema0, 3);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.openjpa.jdbc.identifier.DBIdentifierUtilImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test092()  throws Throwable  {
      AccessDictionary accessDictionary0 = new AccessDictionary();
      DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(accessDictionary0);
      DBIdentifier dBIdentifier0 = DBIdentifier.newForeignKey((String) null);
      Table table0 = new Table();
      DBIdentifier dBIdentifier1 = dBIdentifierUtilImpl0.getValidIndexIdentifier(dBIdentifier0, table0, 205);
      assertFalse(dBIdentifier1.getIgnoreCase());
  }

  @Test(timeout = 4000)
  public void test093()  throws Throwable  {
      AccessDictionary accessDictionary0 = new AccessDictionary();
      DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(accessDictionary0);
      DBIdentifier dBIdentifier0 = DBIdentifier.newColumn("org.apache.openjpa.jdbc.identifier.DBIdentifierUtilImpl");
      Table table0 = new Table();
      // Undeclared exception!
      try { 
        dBIdentifierUtilImpl0.getValidIndexIdentifier(dBIdentifier0, table0, 3);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.openjpa.jdbc.identifier.DBIdentifierUtilImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test094()  throws Throwable  {
      DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl();
      DBIdentifier dBIdentifier0 = DBIdentifier.NULL;
      DBIdentifier dBIdentifier1 = dBIdentifierUtilImpl0.getValidUniqueIdentifier(dBIdentifier0, (Table) null, 1945);
      assertEquals(DBIdentifier.DBIdentifierType.NULL, dBIdentifier1.getType());
  }

  @Test(timeout = 4000)
  public void test095()  throws Throwable  {
      HerdDBDictionary herdDBDictionary0 = new HerdDBDictionary();
      DBIdentifier dBIdentifier0 = DBIdentifier.newTable("({0}||{1})");
      DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl(herdDBDictionary0);
      Table table0 = new Table();
      // Undeclared exception!
      try { 
        dBIdentifierUtilImpl0.getValidUniqueIdentifier(dBIdentifier0, table0, 128);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.openjpa.jdbc.identifier.DBIdentifierUtilImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test096()  throws Throwable  {
      DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl();
      Table table0 = new Table();
      DBIdentifier dBIdentifier0 = dBIdentifierUtilImpl0.getValidForeignKeyIdentifier((DBIdentifier) null, table0, table0, (-1242));
      assertNull(dBIdentifier0);
  }

  @Test(timeout = 4000)
  public void test097()  throws Throwable  {
      DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl();
      Table table0 = new Table();
      DBIdentifier dBIdentifier0 = DBIdentifier.newCatalog((String) null);
      DBIdentifier dBIdentifier1 = dBIdentifierUtilImpl0.getValidColumnIdentifier(dBIdentifier0, table0, (-2500), false);
      assertSame(dBIdentifier0, dBIdentifier1);
  }

  @Test(timeout = 4000)
  public void test098()  throws Throwable  {
      DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl();
      DBIdentifier dBIdentifier0 = DBIdentifier.newIndex("");
      // Undeclared exception!
      try { 
        dBIdentifierUtilImpl0.getValidColumnIdentifier(dBIdentifier0, (Table) null, 128, false);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.openjpa.jdbc.identifier.DBIdentifierUtilImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test099()  throws Throwable  {
      DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl();
      // Undeclared exception!
      try { 
        dBIdentifierUtilImpl0.toDBName("!T{0*\"5WChBPTfl");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.openjpa.jdbc.identifier.DBIdentifierUtilImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test100()  throws Throwable  {
      DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl();
      String string0 = dBIdentifierUtilImpl0.toDBName((DBIdentifier) null);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test101()  throws Throwable  {
      DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl();
      ConfigurationImpl configurationImpl0 = new ConfigurationImpl();
      // Undeclared exception!
      try { 
        dBIdentifierUtilImpl0.setConfiguration(configurationImpl0);
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // class org.apache.openjpa.lib.conf.ConfigurationImpl cannot be cast to class org.apache.openjpa.jdbc.conf.JDBCConfiguration (org.apache.openjpa.lib.conf.ConfigurationImpl and org.apache.openjpa.jdbc.conf.JDBCConfiguration are in unnamed module of loader org.evosuite.instrumentation.InstrumentingClassLoader @42c45a39)
         //
         verifyException("org.apache.openjpa.jdbc.identifier.DBIdentifierUtilImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test102()  throws Throwable  {
      DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl();
      JDBCConfiguration jDBCConfiguration0 = dBIdentifierUtilImpl0.getConfiguration();
      assertNull(jDBCConfiguration0);
  }

  @Test(timeout = 4000)
  public void test103()  throws Throwable  {
      DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl();
      String string0 = dBIdentifierUtilImpl0.shorten("", 3571);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test104()  throws Throwable  {
      DBIdentifierUtilImpl dBIdentifierUtilImpl0 = new DBIdentifierUtilImpl();
      // Undeclared exception!
      try { 
        dBIdentifierUtilImpl0.toDBName((String) null, true);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.openjpa.jdbc.identifier.DBIdentifierUtilImpl", e);
      }
  }
}
